ALTER TYPE "ReportType" ADD VALUE 'LUCRO_FORNECEDOR';
ALTER TYPE "ReportType" ADD VALUE 'PRODUTOS_PREJUIZO';
ALTER TYPE "ReportType" ADD VALUE 'ESTOQUE_PARADO';
ALTER TYPE "ReportType" ADD VALUE 'CAIXAS_PAPELAO';
